apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amd-gpu-mock.fullname" . }}
  labels:
    {{- include "amd-gpu-mock.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Files.Get (printf "profiles/%s.yaml" .Values.gpu.profile) | nindent 4 }}
