{{- $draApi := include "k8s-gpu-dra-driver.draApiVersion" . -}}
{{- if and .Values.deviceClass.create $draApi }}
---
apiVersion: {{ $draApi }}
kind: DeviceClass
metadata:
  name: gpu.amd.com
spec:
  selectors:
  - cel:
      expression: "device.driver == 'gpu.amd.com'"
{{- end }}
